name: Tournament
version: 1.1-BETA
main: com.nightshadepvp.tournament.Tournament
authors: [Blok]
depend: [Core, ViaVersion, MassiveCore]
description: NightShadePvP Tournament Plugin
website: www.nightshadepvp.com
commands:
  arena:
    description: Arena setup
  kit:
    description: Kit setup
  spectator:
    description: Spectator mode
    aliases: [spec]
  tournament:
    description: Tournament setup
    aliases: [tourney]
